spring.application.name=VotingSystem

spring.datasource.url=jdbc:mysql://localhost:3306/votingsystem?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=user1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MySuperSecretKeyForJWT1234567890
jwt.expiration=86400000

server.port =8081
